service: serverless-demo-2

frameworkVersion: ">=1.8.0 <2.0.0"

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
  
provider:
  name: aws
  region: ap-southeast-1
  stage: dev
          
functions:
  addGamer:
    runtime: python3.8
    handler: python/add-gamer.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
        - Fn::Sub: "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/gamer"
    events:
    - http:
        path: /add-gamer
        method: post
        cors: true
  deleteGamer:
    runtime: python3.8
    handler: python/delete-gamer.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DeleteItem
        Resource:
        - Fn::Sub: "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/gamer"
    events:
    - http:
        path: /delete-gamer
        method: post
        cors: true
  searchGamer:
    runtime: python3.8
    handler: python/search-gamer.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Scan
          - dynamodb:Query
        Resource:
        - Fn::Sub: "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/gamer"
    events:
    - http:
        path: /search-gamer
        method: get
        cors: true
  putAvatarToS3:
    runtime: nodejs12.x
    handler: node/put-avatar-to-S3.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:PutObject
        Resource: "*"
    events:
    - http:
        path: /put-avatar-to-S3
        method: post
        cors: true
  getAvatarToS3:
    runtime: nodejs12.x
    handler: node/get-avatar-from-S3.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:GetObject
        Resource: "*"
    events:
    - http:
        path: /get-avatar-from-S3
        method: get
        cors: true

resources:
  Resources:
    GamerTable: ${file(resources/gamer-table.yml)}
    AvatarS3: ${file(resources/avatar-s3.yml)}
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'

package:
  exclude:
  - .serverless/**
  - resources/**
  - /*.yml